spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.169.226:3306/soomo
    username: soomoUser
    password: soomo159753
  jpa:
    hibernate:
      ddl-auto: update  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: ThisIsDefaultSecretKeyfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfjfj # 256비틍 이상의 키가 필요하다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: SoomoAdmin@gmail.com
cloud:
  aws:
    credentials:
      accessKey: AKIAXEURD3OXIZ6ZT444
      secretKey: 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
    s3:
      bucket: testbucketforsoomo
    region:
      static: ap-northeast-2
    stack:
      auto-: false