spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER_ID}
    password: ${DB_USER_PW}
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: ${JWT_SECRET_KEY} # 256비틍 이상의 키가 필요하다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: SoomoAdmin@gmail.com
cloud:
  aws:
    credentials:
      accessKey: ${CLOWD_ACCESS_KEY}
      secretKey: ${CLOWD_SECRET_KEY}
    s3:
      bucket: ${CLOWD_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto-: false